name: SummerFestival
version: '1.0'
main: com.me1q.summerFestival.SummerFestival
api-version: '1.21'
description: 夏祭りをテーマにしたプラグイン
authors: [ me1q ]
website: https://me1q.com

commands:
  shooting:
    description: Manage shooting game
    usage: /<command> <start|stop|status|help>
    aliases: [ sg ]
  tag:
    description: Manage tag game
    usage: /<command> <start|stop|status|recruit|>
  boatrace:
    description: Manage boat racing game
    usage: /<command> <start|stop|help>
    aliases: [ br ]

permissions:
  summerfestival.shooting:
    description: Permission to use shooting game
    default: true
  summerfestival.tag:
    description: Permission to use tag game
    default: true
  summerfestival.boatrace:
    description: Permission to use boat racing game
    default: true
