name: SummerFestival
version: '2.0'
main: com.me1q.summerFestival.SummerFestival
api-version: '1.21'
description: 夏祭りをテーマにしたプラグイン
authors: [ me1q ]
website: https://me1q.com

commands:
  shooting:
    description: Manage shooting game
    usage: /<command> <start|stop|status|help>
    aliases: [ sg ]
  tag:
    description: Manage tag game
    usage: /<command> <start|stop|status|recruit|>
  boatrace:
    description: Manage boat racing game
    usage: /<command> <start|stop|help>
    aliases: [ br ]
  currency:
    description: Manage currency
    usage: /<command> <balance|add|remove|set>
    aliases: [ money, cur ]
  shop:
    description: Manage shop
    usage: /<command> <spawn|remove|open>

permissions:
  summerfestival.shooting:
    description: Permission to use shooting game
    default: true
  summerfestival.tag:
    description: Permission to use tag game
    default: true
  summerfestival.boatrace:
    description: Permission to use boat racing game
    default: true
  summerfestival.currency.add:
    description: Permission to add currency
    default: op
  summerfestival.currency.remove:
    description: Permission to remove currency
    default: op
  summerfestival.currency.set:
    description: Permission to set currency
    default: op
  summerfestival.shop.spawn:
    description: Permission to spawn shop villager
    default: op
  summerfestival.shop.remove:
    description: Permission to remove shop villager
    default: op
  summerfestival.shop.admin:
    description: Permission to manage shop items
    default: op
